name: AI Pull Request Review

on:
  workflow_call:
    inputs:
      force_refresh:
        description: 'Force refresh analysis (ignore cache)'
        required: false
        default: false
        type: boolean
      script_branch:
        description: 'Branch to download the script from'
        required: false
        default: 'main'
        type: string
    secrets:
      ANTHROPIC_API_KEY:
        required: true
  workflow_dispatch:
    inputs:
      force_refresh:
        description: 'Force refresh analysis (ignore cache)'
        required: false
        default: false
        type: boolean

jobs:
  ai-review:
    runs-on: ubuntu-latest
    environment: ai-review

    steps:
      - name: Debug Event Info
        run: |
          echo "🔍 Event name: ${{ github.event_name }}"
          echo "🔍 Event action: ${{ github.event.action }}"
          if [ "${{ github.event_name }}" = "issue_comment" ]; then
            echo "🔍 Comment body: ${{ github.event.comment.body }}"
            echo "🔍 Is PR: ${{ github.event.issue.pull_request }}"
          fi
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "🔍 Label name: ${{ github.event.label.name }}"
          fi
      
      - name: AI Review Status
        run: |
          if [ "${{ github.event_name }}" = "workflow_call" ]; then
            echo "🤖 AI Review called from external workflow! Running analysis..."
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            if [ "${{ github.event.label.name }}" = "ai-review" ]; then
              echo "🤖 AI Review triggered by label! Running analysis..."
            else
              echo "🤖 AI Review triggered! Running analysis..."
            fi
            echo "📋 This will analyze your PR and post a detailed review comment."
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "🤖 AI Review manually triggered! Running analysis..."
          elif [ "${{ github.event_name }}" = "issue_comment" ]; then
            echo "🤖 AI Review triggered by comment! Running analysis..."
          fi
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests>=2.31.0 anthropic>=0.7.0

      - name: Download AI Reviewer Script
        run: |
          # Use the branch from the input parameter
          BRANCH="${{ inputs.script_branch || 'main' }}"
          echo "Downloading script from branch: $BRANCH"
          curl -o ai_reviewer.py https://raw.githubusercontent.com/decentraland/actions/$BRANCH/scripts/ai_pr_reviewer/index.py

      - name: Run AI PR Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          PR_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          python ai_reviewer.py \
            --pr-number "$PR_NUMBER" \
            --repo-owner "$REPO_OWNER" \
            --repo-name "$REPO_NAME"

      - name: Comment on PR
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          # Debug: Show what we're looking for
          echo "🔍 Looking for PR number: $PR_NUMBER"
          echo "🔍 Search pattern: review_comment_pr_${PR_NUMBER}_*.md"
          echo "🔍 Files in output directory:"
          ls -la output/ || echo "Output directory does not exist"
          echo ""
          
          # Find the generated comment file using exact pattern
          COMMENT_FILE=$(find output -name "review_comment_pr_${PR_NUMBER}_*.md" | head -1)
          echo "🔍 Found file: '$COMMENT_FILE'"
          
          if [ -f "$COMMENT_FILE" ]; then
            echo "✅ Found comment file: $COMMENT_FILE"
            python -c "
          import requests
          import os
          import json
          import sys
          
          # Read comment from the found file
          comment_file = '$COMMENT_FILE'
          with open(comment_file, 'r') as f:
              comment = f.read()
          
          # Post comment
          url = f'https://api.github.com/repos/{os.getenv(\"REPO_OWNER\")}/{os.getenv(\"REPO_NAME\")}/issues/{os.getenv(\"PR_NUMBER\")}/comments'
          headers = {
              'Authorization': f'token {os.getenv(\"GITHUB_TOKEN\")}',
              'Accept': 'application/vnd.github.v3+json'
          }
          data = {'body': comment}
          
          response = requests.post(url, headers=headers, json=data)
          if response.status_code == 201:
              print('✅ Comment posted successfully')
          else:
              print(f'❌ Failed to post comment: {response.status_code}')
              print(f'Response: {response.text}')
          "
          else
            echo "❌ No comment file found in output directory"
            ls -la output/ || echo "Output directory does not exist"
          fi
